### ISSUE TITLE
Limit drone velocity

### ISSUE THREAD

**Issue by YHuniv** [andriyukr/olympe_bridge#6]
Hi ,
I am using Anafi parrot 4K with your Ros package, I tried to limit and change the maximum speed but changing the value in the setAnafi.cfg but didnt work.

Could you help ? 
Thanks by advance

**Comment by andriyukr** [comment]
Hi,

If you are talking about `max_horizontal_speed` parameter, it affects **only** `moveto` and `moveby` commands. So, if you use `rpyt` command, there is no way to limit the horizontal velocity since you provide directly roll and pitch commands and not the velocity commands.

To limit (and also command) the horizontal velocity, you have to implement your own velocity controller or use our [anafi_autonomy](https://github.com/andriyukr/anafi_autonomy) package.

Best,
Andriy
