### ISSUE TITLE
Video stream causes error on ROS noetic

### ISSUE THREAD

**Issue by Helge543** [andriyukr/olympe_bridge#7]
Hi,

I followed the instructions here on github and wanted to run `anafi_ros` with `roslaunch olympe_bridge anafi.launch` but get the error message in the screenshot:

![screenshot_github_1](https://github.com/andriyukr/anafi_ros/assets/87704063/1c1cf6a7-63b2-4e31-a5bc-7e55a98f06f0)

It looks like the thread that starts the video stream is causing this problem (timeout error).

If I comment out the line `self.drone.streaming.start()` the rest of the program runs without any problems.

Since I need the video stream from the drone's camera, I wanted to ask how I can fix this error?

**Comment by andriyukr** [comment]
I strongly recommend using the ROS2 branch of the package since we haven't tested the ROS1 branch with the latest versions of Olympe.

I have commented out the lines which are throwing the error in your case (since they are not critical) and updated the ROS1 branch. I hope it will solve your issue.
If the issue still persists, then you will have to check the modifications done in the ROS2 version and port them to the ROS1 version.

**Comment by Helge543** [comment]
I pulled the changes but unfortunately the error still persists.
Do you know with which last Olympe version the ROS1 branch was tested without errors?
As far as I have seen, the Olympe version used is not mentioned in the paper or in the files.
Thanks.

**Comment by andriyukr** [comment]
It should be **Olympe 7.5.0**.
You can install it by running:

    pip install parrot-olympe==7.5.0

**Comment by Helge543** [comment]
Yes thanks! I just tried successively different versions from 7.7.0, 7.6.0 ... and at 7.5.0 it was a success. It works perfectly fine, now!  I'am getting now the images in my custom ros node. Thanks!
